---
# PGADMIN
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: postgres
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          resources:
            requests:
              memory: "128Mi"
              cpu: "5m"
            limits:
              memory: "128Mi"
              cpu: "10m"
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin@admin.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadmin-secret
                  key: pgadmin-password
            # - name: PGADMIN_PORT
            #   value: "80"
          ports:
            - containerPort: 80
              name: pgadmin-port
---
# PGADMIN SERVICE
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: postgres
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 80
---
# Ingress for host pgadmin.db
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgadmin-ing
  namespace: postgres
  labels:
    app: pgadmin
spec:
  ingressClassName: nginx
  rules:
  - host: pgadmin.db
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-svc
            port:
              number: 9080