---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: python-http-server
        image: python:2.7
        command: ["/bin/bash"]
        args: ["-c", "echo \" Hello from $(hostname)\" > index.html; python -m SimpleHTTPServer 80"]
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: helloworld
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
  - port: 4000
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ing
  namespace: helloworld
spec:
  ingressClassName: nginx
  rules:
  - host: helloworld.k8s.cluster
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-svc
            port:
              number: 4000

